### ISSUE TITLE
Opera updated, can no longer use NieR mod.

### ISSUE THREAD

**Issue by Bleggman** [G3NSVRV/OperaGXMods#2]
Opera updated, NieR mod gone, went to reinstall it and this pops up: Something went wrong: \n Package is invalid. Details: ''.

**Comment by g3nsvrv** [comment]
hey, thanks for let me know. I opened a question on the operagx discord to see if they know something or can fix it.
I haven't updated this mode in a while, and far as I checked, no changes has been proposed to the development of mods.
https://github.com/opera-gaming/gxmods/issues/170

**Comment by Maxinellie** [comment]
I can't add the mod

**Comment by Scoltren** [comment]
I really hope this gets fixed soon, this is by far the best GX mod for a NieR:Automata theme :)

**Comment by Maxinellie** [comment]
> I really hope this gets fixed soon, this is by far the best GX mod for a NieR:Automata theme :)

yeah, it's so beautiful

**Comment by Scoltren** [comment]
I really hope the game gets a sequel one day

**Comment by g3nsvrv** [comment]
Yo everyone,
This seems to be a problem with Opera on their latest version. I will keep you updated when this mod is available again.

In the meantime, you can download this repo, and import it yourself using the development mode on the mods screen.

**Comment by Scoltren** [comment]
All your efforts are appreciated good sir, I'll wait until it gets fixed

**Comment by g3nsvrv** [comment]
hi Everyone, I think I found the issue. There was no official notification whatsoever about this change but my theme was failing because the manifest.json had an empty key which was the "shaders", which I disabled it long time ago but I leaved the key if I would use in the future.

This key never had any issues until now with the latest version of operagx (LVL5, core: 104.0.4944.60).

I gonna upload a new version of the mod, it should be available soon with the version `1.1.2`.

https://github.com/opera-gaming/gxmods/issues/170

Thanks to everyone who reported this issue through here and the operagx store website <3.

**Comment by g3nsvrv** [comment]
@Bleggman @Maxinellie @Scoltren happy holydays:
https://store.gx.me/mods/uk1e5e/nier-automata-mod-/

**Comment by Scoltren** [comment]
thank you very much and happy holidays to you too!!<3

**Comment by Bleggman** [comment]
thanks bro great mod, happy holidays
